/Users/ian/zz64/ghc-7.6.3/inplace/lib/haddock -B/Users/ian/zz64/ghc-7.6.3/inplace/lib -l/Users/ian/zz64/ghc-7.6.3/inplace/lib --odir=libraries/array/dist-install/doc/html/array --no-tmp-comp-dir --dump-interface=libraries/array/dist-install/doc/html/array/array.haddock --html --hoogle --title=array-0.4.0.1: Mutable and immutable arrays --prologue=libraries/array/dist-install/haddock-prologue.txt --read-interface=../base-4.6.0.1,../base-4.6.0.1/src/%{MODULE/./-}.html#%{NAME},libraries/base/dist-install/doc/html/base/base.haddock --optghc=-H32m --optghc=-O --optghc=-package-name --optghc=array-0.4.0.1 --optghc=-hide-all-packages --optghc=-i --optghc=-ilibraries/array/. --optghc=-ilibraries/array/dist-install/build --optghc=-ilibraries/array/dist-install/build/autogen --optghc=-Ilibraries/array/dist-install/build --optghc=-Ilibraries/array/dist-install/build/autogen --optghc=-Ilibraries/array/include --optghc=-optP-include --optghc=-optPlibraries/array/dist-install/build/autogen/cabal_macros.h --optghc=-package --optghc=base-4.6.0.1 --optghc=-split-objs --optghc=-XHaskell98 --optghc=-XMultiParamTypeClasses --optghc=-XFlexibleContexts --optghc=-XFlexibleInstances --optghc=-XTypeSynonymInstances --optghc=-XDeriveDataTypeable --optghc=-XStandaloneDeriving --optghc=-XRank2Types --optghc=-XMagicHash --optghc=-XUnboxedTuples --optghc=-XForeignFunctionInterface --optghc=-XUnliftedFFITypes --optghc=-XCPP --optghc=-O2 --optghc=-no-user-package-db --optghc=-rtsopts --optghc=-odir --optghc=libraries/array/dist-install/build --optghc=-hidir --optghc=libraries/array/dist-install/build --optghc=-stubdir --optghc=libraries/array/dist-install/build --optghc=-hisuf --optghc=hi --optghc=-osuf --optghc=o --optghc=-hcsuf --optghc=hc --source-module=src/%{MODULE/./-}.html --source-entity=src/%{MODULE/./-}.html#%{NAME} libraries/array/./Data/Array/Base.hs libraries/array/./Data/Array/IArray.hs libraries/array/./Data/Array/IO.hs libraries/array/./Data/Array/IO/Safe.hs libraries/array/./Data/Array/IO/Internals.hs libraries/array/./Data/Array/MArray.hs libraries/array/./Data/Array/MArray/Safe.hs libraries/array/./Data/Array/ST.hs libraries/array/./Data/Array/ST/Safe.hs libraries/array/./Data/Array/Storable.hs libraries/array/./Data/Array/Storable/Safe.hs libraries/array/./Data/Array/Storable/Internals.hs libraries/array/./Data/Array/Unboxed.hs libraries/array/./Data/Array/Unsafe.hs libraries/array/./Data/Array.hs +RTS -tlibraries/array/dist-install/doc/html/array/array.haddock.t --machine-readable 
 [("bytes allocated", "597245912")
 ,("num_GCs", "594")
 ,("average_bytes_used", "12654477")
 ,("max_bytes_used", "30899144")
 ,("num_byte_usage_samples", "6")
 ,("peak_megabytes_allocated", "73")
 ,("init_cpu_seconds", "0.00")
 ,("init_wall_seconds", "0.00")
 ,("mutator_cpu_seconds", "0.44")
 ,("mutator_wall_seconds", "1.34")
 ,("GC_cpu_seconds", "0.36")
 ,("GC_wall_seconds", "0.38")
 ]
