/Users/ian/zz64/ghc-7.6.3/inplace/lib/haddock -B/Users/ian/zz64/ghc-7.6.3/inplace/lib -l/Users/ian/zz64/ghc-7.6.3/inplace/lib --odir=libraries/template-haskell/dist-install/doc/html/template-haskell --no-tmp-comp-dir --dump-interface=libraries/template-haskell/dist-install/doc/html/template-haskell/template-haskell.haddock --html --hoogle --title=template-haskell-2.8.0.0 --prologue=libraries/template-haskell/dist-install/haddock-prologue.txt --read-interface=../base-4.6.0.1,../base-4.6.0.1/src/%{MODULE/./-}.html#%{NAME},libraries/base/dist-install/doc/html/base/base.haddock --read-interface=../containers-0.5.0.0,../containers-0.5.0.0/src/%{MODULE/./-}.html#%{NAME},libraries/containers/dist-install/doc/html/containers/containers.haddock --read-interface=../pretty-1.1.1.0,../pretty-1.1.1.0/src/%{MODULE/./-}.html#%{NAME},libraries/pretty/dist-install/doc/html/pretty/pretty.haddock --optghc=-H32m --optghc=-O --optghc=-package-name --optghc=template-haskell-2.8.0.0 --optghc=-hide-all-packages --optghc=-i --optghc=-ilibraries/template-haskell/. --optghc=-ilibraries/template-haskell/dist-install/build --optghc=-ilibraries/template-haskell/dist-install/build/autogen --optghc=-Ilibraries/template-haskell/dist-install/build --optghc=-Ilibraries/template-haskell/dist-install/build/autogen --optghc=-Ilibraries/template-haskell/. --optghc=-optP-include --optghc=-optPlibraries/template-haskell/dist-install/build/autogen/cabal_macros.h --optghc=-package --optghc=base-4.6.0.1 --optghc=-package --optghc=containers-0.5.0.0 --optghc=-package --optghc=pretty-1.1.1.0 --optghc=-split-objs --optghc=-package-name --optghc=template-haskell --optghc=-XHaskell98 --optghc=-XMagicHash --optghc=-XPatternGuards --optghc=-XPolymorphicComponents --optghc=-XDeriveDataTypeable --optghc=-O2 --optghc=-no-user-package-db --optghc=-rtsopts --optghc=-odir --optghc=libraries/template-haskell/dist-install/build --optghc=-hidir --optghc=libraries/template-haskell/dist-install/build --optghc=-stubdir --optghc=libraries/template-haskell/dist-install/build --optghc=-hisuf --optghc=hi --optghc=-osuf --optghc=o --optghc=-hcsuf --optghc=hc --source-module=src/%{MODULE/./-}.html --source-entity=src/%{MODULE/./-}.html#%{NAME} libraries/template-haskell/./Language/Haskell/TH/Syntax.hs libraries/template-haskell/./Language/Haskell/TH/PprLib.hs libraries/template-haskell/./Language/Haskell/TH/Ppr.hs libraries/template-haskell/./Language/Haskell/TH/Lib.hs libraries/template-haskell/./Language/Haskell/TH/Quote.hs libraries/template-haskell/./Language/Haskell/TH.hs +RTS -tlibraries/template-haskell/dist-install/doc/html/template-haskell/template-haskell.haddock.t --machine-readable 
 [("bytes allocated", "780711840")
 ,("num_GCs", "1032")
 ,("average_bytes_used", "15901267")
 ,("max_bytes_used", "36337360")
 ,("num_byte_usage_samples", "7")
 ,("peak_megabytes_allocated", "94")
 ,("init_cpu_seconds", "0.00")
 ,("init_wall_seconds", "0.00")
 ,("mutator_cpu_seconds", "0.48")
 ,("mutator_wall_seconds", "0.59")
 ,("GC_cpu_seconds", "0.45")
 ,("GC_wall_seconds", "0.47")
 ]
