/Users/ian/zz64/ghc-7.6.3/inplace/lib/haddock -B/Users/ian/zz64/ghc-7.6.3/inplace/lib -l/Users/ian/zz64/ghc-7.6.3/inplace/lib --odir=libraries/binary/dist-install/doc/html/binary --no-tmp-comp-dir --dump-interface=libraries/binary/dist-install/doc/html/binary/binary.haddock --html --hoogle --title=binary-0.5.1.1: Binary serialisation for Haskell values using lazy ByteStrings --prologue=libraries/binary/dist-install/haddock-prologue.txt --hide=Data.Binary.Builder.Base --read-interface=../array-0.4.0.1,../array-0.4.0.1/src/%{MODULE/./-}.html#%{NAME},libraries/array/dist-install/doc/html/array/array.haddock --read-interface=../base-4.6.0.1,../base-4.6.0.1/src/%{MODULE/./-}.html#%{NAME},libraries/base/dist-install/doc/html/base/base.haddock --read-interface=../bytestring-0.10.0.2,../bytestring-0.10.0.2/src/%{MODULE/./-}.html#%{NAME},libraries/bytestring/dist-install/doc/html/bytestring/bytestring.haddock --read-interface=../containers-0.5.0.0,../containers-0.5.0.0/src/%{MODULE/./-}.html#%{NAME},libraries/containers/dist-install/doc/html/containers/containers.haddock --optghc=-H32m --optghc=-O --optghc=-package-name --optghc=binary-0.5.1.1 --optghc=-hide-all-packages --optghc=-i --optghc=-ilibraries/binary/src --optghc=-ilibraries/binary/dist-install/build --optghc=-ilibraries/binary/dist-install/build/autogen --optghc=-Ilibraries/binary/dist-install/build --optghc=-Ilibraries/binary/dist-install/build/autogen --optghc=-Ilibraries/binary/. --optghc=-optP-DAPPLICATIVE_IN_BASE --optghc=-optP-include --optghc=-optPlibraries/binary/dist-install/build/autogen/cabal_macros.h --optghc=-package --optghc=array-0.4.0.1 --optghc=-package --optghc=base-4.6.0.1 --optghc=-package --optghc=bytestring-0.10.0.2 --optghc=-package --optghc=containers-0.5.0.0 --optghc=-split-objs --optghc=-O2 --optghc=-Wall --optghc=-fliberate-case-threshold=1000 --optghc=-XHaskell98 --optghc=-XCPP --optghc=-XFlexibleContexts --optghc=-O2 --optghc=-no-user-package-db --optghc=-rtsopts --optghc=-odir --optghc=libraries/binary/dist-install/build --optghc=-hidir --optghc=libraries/binary/dist-install/build --optghc=-stubdir --optghc=libraries/binary/dist-install/build --optghc=-hisuf --optghc=hi --optghc=-osuf --optghc=o --optghc=-hcsuf --optghc=hc --source-module=src/%{MODULE/./-}.html --source-entity=src/%{MODULE/./-}.html#%{NAME} libraries/binary/src/Data/Binary.hs libraries/binary/src/Data/Binary/Put.hs libraries/binary/src/Data/Binary/Get.hs libraries/binary/src/Data/Binary/Builder.hs libraries/binary/src/Data/Binary/Builder/Internal.hs libraries/binary/src/Data/Binary/Builder/Base.hs +RTS -tlibraries/binary/dist-install/doc/html/binary/binary.haddock.t --machine-readable 
 [("bytes allocated", "416739280")
 ,("num_GCs", "428")
 ,("average_bytes_used", "17135260")
 ,("max_bytes_used", "44569032")
 ,("num_byte_usage_samples", "6")
 ,("peak_megabytes_allocated", "93")
 ,("init_cpu_seconds", "0.00")
 ,("init_wall_seconds", "0.00")
 ,("mutator_cpu_seconds", "0.29")
 ,("mutator_wall_seconds", "0.81")
 ,("GC_cpu_seconds", "0.36")
 ,("GC_wall_seconds", "0.38")
 ]
